---
# https://stackoverflow.com/questions/38647864/ansible-grab-a-key-from-a-dictionary-but-not-in-a-loop
az_resource_group: cloud-msp-gitlab-demo
az_location: ukwest
az_publicipaddress_method: 'Static'
az_admin_username: 'cloud_user'
az_ssh_password_enabled: 'False'
az_ssh_private_key: "~/.ssh/cloud_user_id_rsa"
az_ssh_public_key: "~/.ssh/cloud_user_id_rsa.pub"
verbosity_level: 0

az_images:
  - offer: CentOS
    publisher: OpenLogic
    sku: '7.3'
    version: latest 

az_virtualnetworks:
  - name: cloud-msp-gitlab-demo-net
    address_prefixes: "10.0.0.0/16"
    resource_group: "{{ az_resource_group }}"

az_subnets:
  - name: "cloud-msp-gitlab-demo-subnet"
    address_prefix: "10.0.1.0/24"
    virtual_network: "{{ az_virtualnetworks[0].name }}"
    resource_group: "{{ az_resource_group }}"

az_public_ips:
  - name: cloud-msp-gitlab-demo-ansible-publicip
    allocation_method: "{{ az_publicipaddress_method }}"
    resource_group: "{{ az_resource_group }}"
  - name: cloud-msp-gitlab-demo-gitlab-publicip
    allocation_method: "{{ az_publicipaddress_method }}"
    resource_group: "{{ az_resource_group }}"

az_securitygroup_name: "cloud-msp-gitlab-demo-secgroup"
az_securitygroup_rules:
  - name: SSH
    protocol: Tcp
    destination_port_range: 22
    access: Allow
    priority: 1001
    direction: Inbound
  - name: HTTPS
    protocol: Tcp
    destination_port_range: 443
    access: Allow
    priority: 1002
    direction: Inbound

az_networkinterfaces:
  - name: cloud-msp-gitlab-demo-ansible-nic
    resource_group: "{{ az_resource_group }}"
    virtual_network: "{{ az_virtualnetworks[0].name }}"
    subnet: "{{ az_subnets[0].name }}"
    public_ip_name: "{{ az_public_ips[0].name }}"
    security_group: "{{ az_securitygroup_name }}"
  - name: cloud-msp-gitlab-demo-gitlab-nic
    resource_group: "{{ az_resource_group }}"
    virtual_network: "{{ az_virtualnetworks[0].name }}"
    subnet: "{{ az_subnets[0].name }}"
    public_ip_name: "{{ az_public_ips[1].name }}"
    security_group: "{{ az_securitygroup_name }}"

az_vms:
  - name: ansiblevm
    resource_group: "{{ az_resource_group }}"
    # vm_size: 'Basic_A0'
    vm_size: 'Standard_A2'
    admin_username: "{{ az_admin_username }}"
    ssh_password_enabled: "{{ az_ssh_password_enabled }}"
    ssh_public_keys:
      - path:  "~/.ssh/authorized_keys"
        key_data: "{{ lookup('file', az_ssh_public_key) }}"
    network_interfaces: "{{ az_networkinterfaces[0].name }}"
    # image: "{{ az_images['centos'] }}"
    image: "{{ az_images[0] }}"
    tags:
      role: 'ansible'
  - name: gitlabvm
    resource_group: "{{ az_resource_group }}"
    # vm_size: 'Basic_A0'
    vm_size: 'Standard_A2'
    admin_username: "{{ az_admin_username }}"
    ssh_password_enabled: "{{ az_ssh_password_enabled }}"
    ssh_public_keys:
      - path:  "~/.ssh/authorized_keys"
        key_data: "{{ lookup('file', az_ssh_public_key) }}"
    network_interfaces: "{{ az_networkinterfaces[1].name }}"
    # image: "{{ az_images['centos'] }}"
    image: "{{ az_images[0] }}"
    tags:
      role: 'gitlab'

    
