---
awx_external_hostname: ansible
awx_fqdn: "{{ awx_external_hostname }}.{{ cloud_domain }}"
nodejs_version: "6.x"
pip_install_packages:
  - name: docker-py

ansible_copy_certs: "true"
ansible_certs:
  - src: "~/certs/ansible.cloud-msp.net/cert.pem"
    dest: "/etc/ssl/certs/certificate.pem"
  - src: "~/certs/ansible.cloud-msp.net/privkey.pem"
    dest: "/etc/ssl/certs/certificate.key"

