---
- name: Deploy azure resource manager group
  hosts: localhost
  connection: local
  tags:
    - azure

  roles:

  - name: azure VM provisioning
    role: azure_rm_group
    tags:
      - azure
      - deploy

  post_tasks:

  - name: deployment variable
    debug:
      var: azure_deployment

  - name: refresh the inventory
    meta: refresh_inventory
    tags:
      - azure
      - inventory

  - name: display groups
    debug:
      var: groups

  - name: set fact for public ip of ansible awx server
    set_fact:
      ansible_public_ip: "{{  hostvars[az_ansible_vm_name]['public_ip'] }}"

  - name: set fact for use with ansible-role-awx-default-password role for tower-cli
    set_fact:
      awx_host: "http://{{ ansible_public_ip }}"

  - name: debug public ip facts
    debug:
      var: item
    with_items:
      - "{{ ansible_public_ip }}"
      - "{{ awx_host }}"

- name:  Deploy server roles
  hosts: role_ansible
  strategy: free

  pre_tasks:

  - name: wait for VMs
    wait_for_connection:
      timeout: 300

  - name: debug ansible_hostname
    debug:
      var: ansible_hostname

  tasks:

  - import_tasks: ansible-awx.yml
    when: "'role_ansible' in group_names"

- name: Configure AWX
  hosts: localhost
  connection: local
  
  roles:
  - ansible-role-awx-default-password

