---
- name: Deploy azure resource manager group
  hosts: localhost
  connection: local
  tags:
    - azure

  roles:

  - name: azure VM provisioning
    role: azure_rm_group
    tags:
      - azure
      - deploy

  post_tasks:

  - name: deployment variable
    debug:
      var: deployment

  - name: refresh the inventory
    meta: refresh_inventory
    tags:
      - azure
      - inventory

  - name: display groups
    debug:
      var: groups

- name:  Deploy server roles
  hosts: role_ansible
  strategy: free

  pre_tasks:

  - name: wait for VMs
    wait_for_connection:
      timeout: 300

  - name: debug ansible_hostname
    debug:
      var: ansible_hostname

  tasks:

  - import_tasks: ansible-awx.yml
    when: "'role_ansible' in group_names"

