---
- name: Deploy azure resource manager group
  hosts: localhost
  connection: local
  tags:
    - azure

  roles:

  - name: azure VM provisioning
    role: azure_rm_group
    tags:
      - azure
      - deploy

  post_tasks:

  - name: refresh the inventory
    meta: refresh_inventory
    tags:
      - azure
      - inventory

