---
- name: Delete Azure Resource Group
  hosts: localhost
  connection: local

  vars:
    az_resource_group: cloud-msp-gitlab-demo
    verbosity_level: 0

  vars_files:
    - roles/azure_vms/defaults/main.yml

  tasks:

  - name: delete resource group
    azure_rm_resourcegroup:
      name: "{{ az_resource_group }}"
      force: yes
      state: absent
    register: azure_resourcegroup
    ignore_errors: True

  - name: debug azure_resourcegroup
    debug: 
      var: azure_resourcegroup
      verbosity: "{{ verbosity_level }}"    

  - name: delete dns azure recordset entries
    azure_rm_dnsrecordset:
      resource_group: "{{ az_dns_resource_group }}"
      relative_name: "{{ item.name }}"
      record_type: A
      zone_name: "{{ az_dnsrecordset_zone_name }}"
      state: absent
    register: azure_dnsrecordset
    with_items: "{{ az_vms }}"

  - name: debug azure_resourcegroup
    debug:
      var: azure_dnsrecordset
      verbosity: "{{ verbosity_level }}"
