---
- name: Testing
  hosts: localhost
  connection: local

  roles:

  - name: azure VM provisioning
    role: azure_vms
    tags:
      - azure
      - provision

  post_tasks:

  - name: refresh the inventory
    meta: refresh_inventory
    tags:
      - inventory

- name: Deploy GitLab
  hosts: gitlab
  gather_facts: False
  become: yes

  pre_tasks:

  - name: wait for VMs
    wait_for_connection:
      timeout: 300
    tags:
      - gitlab

  - name: now gather facts
    setup:
    tags:
      - facts
      - gitlab

  - name: debug some variable
    debug:
      var: hostvars[inventory_hostname]['ansible_os_family']
      verbosity: "{{ verbosity_level }}"
    tags:
      - gitlab

  roles:
  
  - name: deploy gitlab
    role: ansible-role-gitlab
    tags:
      - gitlab
      - deploy

- name: Deploy AWX
  hosts: ansible
  gather_facts: False
  become: yes

  pre_tasks:

  - name: wait for VMs
    wait_for_connection:
      timeout: 300

  - name: now gather facts
    setup:

  roles:

  - name: configure epel repo
    role: ansible-role-repo-epel 

  - name: install git
    role: ansible-role-git

  - name: install ansible
    role: ansible-role-ansible

  - name: install docker
    role: ansible-role-docker

  - name: install pip
    role: ansible-role-pip

  - name: install nodejs
    role: ansible-role-nodejs

  - name: install awx
    role: ansible-role-awx
