---
- name: Testing
  hosts: localhost
  connection: local

  roles:

  - role: azure_vms

- name: Testing Access
  hosts: azure

  tasks:

  - name: debug some variable
    debug:
      var: hostvars[inventory_hostname]['ansible_os_family']

