---
- name: Delete Azure Resource Group
  hosts: localhost
  connection: local

  vars:
    az_resource_group: cloud-msp-gitlab-demo
    verbosity_level: 0

  tasks:

  - name: delete resource group
    azure_rm_resourcegroup:
      name: "{{ az_resource_group }}"
      force: yes
      state: absent
    register: azure_resourcegroup

  - name: Debug azure_resourcegroup
    debug: 
      var: azure_resourcegroup
      verbosity: "{{ verbosity_level }}"    

