---
- name: Deploy GitLab
  hosts: gitlabvm
  gather_facts: False

  pre_tasks:

  - name: wait for VMs
    wait_for_connection:
      timeout: 300

  - name: now gather facts
    setup:
    tags:
      - facts

  - name: debug some variable
    debug:
      # var: hostvars[inventory_hostname]['ansible_os_family']
      var: hostvars[inventory_hostname]

