---
- name: DNS record test
  hosts: localhost
  connection: local

  vars_files:
    - roles/azure_vms/defaults/main.yml

  tasks:

#  - name: create VMs
#    azure_rm_virtualmachine:
#      resource_group: "{{ item.resource_group }}"
#      name: "{{ item.name }}"
#      vm_size: "{{ item.vm_size }}"
#      admin_username: "{{ item.admin_username }}"
#      ssh_password_enabled: "{{ az_ssh_password_enabled }}"
#      ssh_public_keys:
#      - path: "/home/{{ az_admin_username }}/.ssh/authorized_keys"
#        key_data: "{{ lookup('file', az_ssh_public_key) }}"
#      network_interfaces: "{{ item.network_interfaces }}"
#      image: "{{ item.image }}"
#      append_tags: no
#    register: azure_virtualmachines
#    with_items: "{{ az_vms }}" 

#  - name: create facts for DNS entries
#    vars:
#      az_dns_name: "{{ item.ansible_facts.azure_vm.name }}"
#      az_dns_ip_address: "{{ item.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
#    set_fact:
#      az_dnsrecordsets: "{{ az_dnsrecordsets | default([]) + [ { 'name': az_dns_name, 'type': 'A', 'records': [ { 'entry': az_dns_ip_address }] } ] }}"
#    with_items: "{{ azure_virtualmachines.results }}"
#    when:
#      - az_dnsrecordset_create is defined
#      - az_dnsrecordset_create

#  - name: debug az_dnsrecordsets
#    debug:
#      var: az_dnsrecordsets
#      verbosity: "{{ verbosity_level }}"
#    when:
#      - az_dnsrecordset_create is defined
#      - az_dnsrecordset_create

#  - name: debug messages
#    debug:
#      msg: "Name: {{ item.name }}, Type: {{ item.type }}, Records: {{ item.records }}"
#    with_items: "{{ az_dnsrecordsets }}"

  #- name: create "A" record sets
  #  azure_rm_dnsrecordset:
  #    resource_group: "{{ az_dns_resource_group }}"
  #    zone_name: "{{ az_dnsrecordset_zone_name }}"
  #    state: present
  #    relative_name: "{{ item.name }}"
  #    record_type: "{{ item.type }}"
  #    records: "{{ item.records }}"
  #  register: azure_dnsrecordsets
  #  # with_items: "{{ az_dnsrecordsets }}"
  #  with_items:
  #    - { name: 'ansible', type: 'A', records: [ { entry: '51.141.25.126' }] }
  #    - { name: 'serverb', type: 'A', records: [ { entry: '51.141.38.228' }] }
   # when:
   #   - az_dnsrecordset_create is defined
   #   - az_dnsrecordset_create

  - name: ensure an "A" record set with multiple records
    azure_rm_dnsrecordset:
      resource_group: cloud-msp.net
      relative_name: ansibletest
      zone_name: cloud-msp.net
      record_type: A
      state: present
      records:
        - entry: 51.141.25.126
    register: azure_dnsrecordsets

  - name: debug azure_dnsrecordsets
    debug:
      var: azure_dnsrecordsets
      verbosity: "{{ verbosity_level }}"
    when:
      - az_dnsrecordset_create is defined
      - az_dnsrecordset_create

