---
jumphost_user:
  name: ansible_user
  password: D0ntPutH3r3
  state: present
  comment: "Ansible user"
  createhome: yes
  sudoer_entry: "ALL=(ALL)       NOPASSWD: ALL"
  expiredate: -1
  maxdays: -1

jumphost_packages:
  - putty

jumphost_copy_certs: "true"
jumphost_certs:
  - src: "~/jumphost.cloud-msp.net/certs/cert.pem"
    dest: "/etc/ssl/certs/certificate.pem"
  - src: "~/jumphost.cloud-msp.net/certs/privkey.pem"
    dest: "/etc/ssl/certs/certificate.key"
