---
jumphost_hostname: jumphost
jumphost_fqdn: jumphost.cloud-msp.net
shellinabox_apache_fqdn: "{{ jumphost_fqdn }}"
# ansible-role-apach variable to not start service
apache_state: stopped

jumphost_user:
  name: ansible_user
  password: D0ntPutH3r3
  state: present
  comment: "Ansible user"
  createhome: yes
  sudoer_entry: "ALL=(ALL)       NOPASSWD: ALL"
  expiredate: -1
  maxdays: -1

jumphost_packages:
  - putty

jumphost_copy_certs: "true"
jumphost_certs:
  - src: "~/certs/jumphost.cloud-msp.net/cert.pem"
    dest: "/etc/ssl/certs/certificate.pem"
  - src: "~/certs/jumphost.cloud-msp.net/privkey.pem"
    dest: "/etc/ssl/certs/certificate.key"
