---

- name: Create Azure Deploy
  azure_rm_deployment:
    state: present
    resource_group_name: "{{ az_resource_group }}"
    template_link: "{{ az_template_link }}"
    # parameters_link: "{{ az_parameters_link }}"

- name: debug deployment
  debug:
    var: deployment
    verbosity: "{{ verbosity_level }}"


- name: create "A" record sets 
  azure_rm_dnsrecordset:
    resource_group: "{{ az_dns_resource_group }}"
    zone_name: "{{ az_dnsrecordset_zone_name }}"
    state: present
    relative_name: "{{ item.name }}"
    record_type: "{{ item.type }}"
    records: "{{ item.records }}"
  register: azure_dnsrecordsets
  with_items: "{{ az_dnsrecordsets }}"
  when:
    - az_dnsrecordset_create is defined
    - az_dnsrecordset_create

- name: debug azure_dnsrecordsets
  debug:
    var: azure_dnsrecordsets
    verbosity: "{{ verbosity_level }}"
  when:
    - az_dnsrecordset_create is defined
    - az_dnsrecordset_create
