---
# https://stackoverflow.com/questions/38647864/ansible-grab-a-key-from-a-dictionary-but-not-in-a-loop
az_resource_group: ansible-demo-rg
az_location: ukwest
az_publicipaddress_method: 'Static'
az_admin_username: 'cloud_user'
az_ssh_password_enabled: 'False'
az_ssh_private_key: "~/.ssh/cloud_user_id_rsa"
az_ssh_public_key: "~/.ssh/cloud_user_id_rsa.pub"
az_dnsrecordset_create: True
az_dns_resource_group: cloud-msp.net
az_dnsrecordset_zone_name: cloud-msp.net
az_rg_state: present
az_environment: dev
az_ansible_vm_size: "Standard_A2"
az_jumphost_vm_size: "Basic_A2"
az_docker_vm_size: "Basic_A3"
verbosity_level: 0

az_parameters_link: https://github.com/tonyskidmore/cloud-msp/blob/master/examples/ansible_azure_ansible_demo/files/azuredeploy.parameters.json
az_template_link: https://raw.githubusercontent.com/tonyskidmore/cloud-msp/master/examples/ansible_azure_ansible_demo/files/azuredeploy.json
az_rm_parameters:
  adminUsername:
    value: "{{ az_admin_username }}"
  sshKeyData:
    value: "{{ lookup('file', az_ssh_public_key) }}"
  ansibleVmSize:
    value: "{{ az_ansible_vm_size }}"
  jumphostVmSize:
    value: "{{ az_jumphost_vm_size }}"
  dockerVmSize:
    value: "{{ az_docker_vm_size }}"
  environment:
    value: "{{ az_environment }}"

